[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
default-run = "app"
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = [] }

[dependencies]
sysinfo = "0.23"
serde_json = "1"
serde = { version = "^1.0", features = ["derive"] }
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["api-all", "updater"] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/tauri-plugin-window-state" }
open = "2"
path-absolutize = "3"
trash = "2"
notify = "4"
normpath = "0.3"
lazy_static = "1.4"
font-loader = "0.11"
clap = "3.0.14"
glob = "0.3"
parselnk = "0.1"
url = "2.2"
reqwest = "0.11"
tokio = { version = "^1", features = ["macros", "parking_lot", "rt"] }
bincode = "1.3"

[target."cfg(any(target_os = \"windows\", target_os = \"macos\"))".dependencies]
tauri-plugin-vibrancy = { git = "https://github.com/tauri-apps/tauri-plugin-vibrancy", features = ["tauri-impl"] }
tauri-plugin-shadows = { git = "https://github.com/tauri-apps/tauri-plugin-shadows", features = ["tauri-impl"], rev = "bf34e300d238ea4519dab3220ff8c76f07701a93" }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
